export const DETAIL_MOVIE = "DETAIL_MOVIE";
export const PUT_DETAIL_MOVIE = "PUT_DETAIL_MOVIE";
export const SET_LOADING_ID = "SET_LOADING_ID";

export const MOVIE_ALL = "MOVIE_ALL";
export const MOVIE_CATEGORY = "MOVIE_CATEGORY";
export const PUT_MOVIE_CATEGORY = "PUT_MOVIE_CATEGORY";